name: Create or Overwrite ECR Repository

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: eu-west-2
  ECR_REPOSITORY_NAME: my-ecr-repository

jobs:
  create-or-overwrite-ecr-repository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Delete existing ECR repository
      run: |
        set +e
        aws ecr delete-repository --repository-name $ECR_REPOSITORY_NAME --force
        set -e

    - name: Create ECR repository
      run: |
        aws ecr create-repository --repository-name $ECR_REPOSITORY_NAME
        
        
        
    - name: Authenticate Docker to ECR
      run: |
        # Retrieve an authentication token and authenticate Docker client to ECR
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 438337256072.dkr.ecr.eu-west-2.amazonaws.com
        
        
        
    - name: Build Docker image
      run: |
        # Build Docker image and tag it with ECR repository name
        docker build -t my-ecr-repository .


